### ISSUE TITLE
Versioning of the uds-package is based off the chart when it should be based off the application

### ISSUE THREAD

**Issue by anthonywendt** [defenseunicorns/uds-package-confluence#33]
Currently the version of this uds-package matches the chart. Our other uds-package(s) tend to have the first part of their version match the applications version. That doesn't always match the chart version.

See [Gitlab](https://github.com/defenseunicorns/uds-package-gitlab) for example

**Comment by Michael-Kruggel** [comment]
Fixed this with the latest release
